name: Unit Testing

on:
  pull_request:
    branches: '*'
  push:
    branches:
      - master
      - develop

jobs:
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    container:
      image: atk4/image:${{ matrix.php }} # https://github.com/atk4/image
    strategy:
      matrix:
        php: ['7.2', '7.3', 'latest']
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: atk4_pass
          MYSQL_USER: atk4_test
          MYSQL_PASSWORD: atk4_pass
          MYSQL_DATABASE: atk4_test__audit
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v2
      - run: php --version
      # need this to trick composer
      # - run: "git branch develop; git checkout develop"
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Init
        run: |
          mkdir -p build/logs
          cp demos/include/db.example.php demos/include/db.php

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --configuration phpunit.xml --coverage-text

      - uses: codecov/codecov-action@v1
        if: matrix.php == 'latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/logs/clover.xml
